const LECTURE_DATA = [
  {
    "id": 1,
    "subject": "컨셉캐릭터일러 (비대면)",
    "instructor": "이재건",
    "room": "M",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 2,
    "subject": "원화시트실무",
    "instructor": "이재건",
    "room": "M",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-05 ~ 01-26",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 3,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 4,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 5,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 6,
    "subject": "게임아트웍",
    "instructor": "심예지",
    "room": "O",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 7,
    "subject": "게임아트웍",
    "instructor": "심예지",
    "room": "O",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 8,
    "subject": "게임원화",
    "instructor": "심예지",
    "room": "O",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 9,
    "subject": "컴퓨터그래픽스1",
    "instructor": "김홍규",
    "room": "P",
    "startH": 11,
    "endH": 13,
    "days": "월/수/금",
    "dateInfo": "01-02 ~ 01-21",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 10,
    "subject": "컴퓨터그래픽스2",
    "instructor": "김홍규",
    "room": "P",
    "startH": 11,
    "endH": 13,
    "days": "월/수/금",
    "dateInfo": "01-23 ~ 02-11",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 11,
    "subject": "게임프로그래밍포폴",
    "instructor": "김홍규",
    "room": "P",
    "startH": 14,
    "endH": 16,
    "days": "화/목",
    "dateInfo": "12-16 ~ 01-15",
    "category": "port",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 12,
    "subject": "게임기획3",
    "instructor": "전태은",
    "room": "P",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "plan-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 13,
    "subject": "게임기획8",
    "instructor": "전태은",
    "room": "P",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "plan-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 14,
    "subject": "게임기획1",
    "instructor": "전태은",
    "room": "P",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "plan-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 15,
    "subject": "[국] 게임그래픽 전문가양성",
    "instructor": "최동훈",
    "room": "L",
    "startH": 9,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "12-01 ~ 07-01",
    "category": "kdigital",
    "weekType": "ALL",
    "isBadge": "국비",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 16,
    "subject": "게임프로그래밍2",
    "instructor": "최대호",
    "room": "L",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 17,
    "subject": "게임프로그래밍5",
    "instructor": "최대호",
    "room": "L",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 18,
    "subject": "게임프로그래밍1",
    "instructor": "최대호",
    "room": "L",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 19,
    "subject": "게임원화",
    "instructor": "조성진",
    "room": "N",
    "startH": 11,
    "endH": 13,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 20,
    "subject": "게임아트웍",
    "instructor": "조성진",
    "room": "N",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 21,
    "subject": "C++",
    "instructor": "김홍규",
    "room": "N",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "12-18 ~ 01-14",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 22,
    "subject": "게임아트웍",
    "instructor": "조성진",
    "room": "N",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 23,
    "subject": "게임원화(심화)",
    "instructor": "조성진",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-02",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 24,
    "subject": "게임아트웍(기초)",
    "instructor": "조성진",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "화/목",
    "dateInfo": "01-13 ~ 02-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 25,
    "subject": "게임그래픽(기초)",
    "instructor": "김지원",
    "room": "Q",
    "startH": 11,
    "endH": 13,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 26,
    "subject": "게임그래픽(심화)",
    "instructor": "김지원",
    "room": "Q",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 27,
    "subject": "게임그래픽(심화)",
    "instructor": "김지원",
    "room": "Q",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 28,
    "subject": "게임그래픽(기초)",
    "instructor": "김지원",
    "room": "Q",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 29,
    "subject": "게임아트웍(기초)",
    "instructor": "이재건",
    "room": "Q",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-13 ~ 02-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 30,
    "subject": "게임원화(심화)",
    "instructor": "이재건",
    "room": "Q",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-02",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 31,
    "subject": "게임아트웍",
    "instructor": "김채민",
    "room": "R",
    "startH": 11,
    "endH": 13,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 32,
    "subject": "게임원화",
    "instructor": "김채민",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 33,
    "subject": "게임원화",
    "instructor": "김채민",
    "room": "R",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 34,
    "subject": "게임아트웍",
    "instructor": "김채민",
    "room": "R",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 35,
    "subject": "웹툰기초",
    "instructor": "이상원",
    "room": "R",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "01-05 ~ 01-22",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 36,
    "subject": "게임아트웍(기초)",
    "instructor": "김지원",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-02",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 37,
    "subject": "게임원화(심화)",
    "instructor": "이상원",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "01-13 ~ 02-05",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 38,
    "subject": "고등부팀프로젝트반",
    "instructor": "전태은",
    "room": "S",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-05 ~ 01-26",
    "category": "port",
    "weekType": "ALL",
    "isBadge": "YOUTH",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 39,
    "subject": "웹툰기초드로잉",
    "instructor": "이상원",
    "room": "S",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-12 ~ 02-04",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 40,
    "subject": "AI프롬프트드로잉",
    "instructor": "이재건",
    "room": "S",
    "startH": 18,
    "endH": 20,
    "days": "월/수/금",
    "dateInfo": "01-12 ~ 01-30",
    "category": "art-basic",
    "weekType": "B",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 41,
    "subject": "AI프롬프트드로잉",
    "instructor": "이재건",
    "room": "S",
    "startH": 18,
    "endH": 20,
    "days": "화/목",
    "dateInfo": "01-15 ~ 02-10",
    "category": "art-basic",
    "weekType": "A",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 42,
    "subject": "게임UIUX",
    "instructor": "김창욱",
    "room": "S",
    "startH": 20,
    "endH": 22,
    "days": "월/수/금",
    "dateInfo": "01-12 ~ 02-06",
    "category": "ui",
    "weekType": "A",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 43,
    "subject": "이모티콘",
    "instructor": "김창욱",
    "room": "S",
    "startH": 20,
    "endH": 22,
    "days": "화/목",
    "dateInfo": "01-12 ~ 02-04",
    "category": "emo",
    "weekType": "B",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  }
];