const LECTURE_DATA = [
  {
    "id": 1,
    "subject": "웹툰",
    "instructor": "손윤식",
    "room": "M",
    "startH": 12,
    "endH": 18,
    "days": "토",
    "dateInfo": "12-27 ~ 01-17",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 2,
    "subject": "웹툰",
    "instructor": "김재동",
    "room": "M",
    "startH": 12,
    "endH": 18,
    "days": "일",
    "dateInfo": "12-28 ~ 01-18",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 3,
    "subject": "웹툰",
    "instructor": "손윤식",
    "room": "M",
    "startH": 12,
    "endH": 18,
    "days": "토",
    "dateInfo": "01-24 ~ 02-14",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 4,
    "subject": "웹툰",
    "instructor": "김재동",
    "room": "M",
    "startH":12,
    "endH": 18,
    "days": "일",
    "dateInfo": "01-25 ~ 02-15",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 5,
    "subject": "게임원화",
    "instructor": "정예지",
    "room": "O",
    "startH": 9,
    "endH": 13,
    "days": "토/일",
    "dateInfo": "01-17 ~ 02-08",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 6,
    "subject": "게임원화",
    "instructor": "정예지",
    "room": "O",
    "startH": 14,
    "endH": 18,
    "days": "토/일",
    "dateInfo": "01-17 ~ 02-08",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 7,
    "subject": "아포리아심화반",
    "instructor": "최준혁",
    "room": "P",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "01-11 ~ 02-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 8,
    "subject": "아포리아심화반",
    "instructor": "최준혁",
    "room": "P",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "02-08 ~ 03-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 9,
    "subject": "게임원화",
    "instructor": "강정완",
    "room": "P",
    "startH": 10,
    "endH": 18,
    "days": "토",
    "dateInfo": "12-27 ~ 01-17",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 10,
    "subject": "게임원화",
    "instructor": "강정완",
    "room": "P",
    "startH": 10,
    "endH": 18,
    "days": "토",
    "dateInfo": "01-24 ~ 02-14",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 11,
    "subject": "아포리아웹툰데뷔반1",
    "instructor": "최준혁",
    "room": "P",
    "startH": 14,
    "endH": 18,
    "days": "일",
    "dateInfo": "02-01 ~ 02-22",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 12,
    "subject": "유니티1",
    "instructor": "윤지현",
    "room": "L",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "01-04 ~ 02-08",
    "category": "programming",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 13,
    "subject": "유니티2",
    "instructor": "김홍규",
    "room": "L",
    "startH": 14,
    "endH": 18,
    "days": "일",
    "dateInfo": "12-14 ~ 01-18",
    "category": "programming",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 14,
    "subject": "유니티3",
    "instructor": "김홍규",
    "room": "L",
    "startH": 14,
    "endH": 18,
    "days": "일",
    "dateInfo": "01-25 ~ 03-01",
    "category": "programming",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 15,
    "subject": "게임원화",
    "instructor": "조성진",
    "room": "N",
    "startH": 10,
    "endH": 18,
    "days": "토",
    "dateInfo": "01-17 ~ 02-07",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 16,
    "subject": "스파인",
    "instructor": "최동훈",
    "room": "Q",
    "startH": 9,
    "endH": 13,
    "days": "토",
    "dateInfo": "01-10 ~ 01-31",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 17,
    "subject": "게임그래픽",
    "instructor": "최동훈",
    "room": "Q",
    "startH": 14,
    "endH": 18,
    "days": "토/일",
    "dateInfo": "01-17 ~ 02-08",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 18,
    "subject": "게프포폴",
    "instructor": "김홍규",
    "room": "Q",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "01-11 ~ 02-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 19,
    "subject": "스파인",
    "instructor": "최동훈",
    "room": "Q",
    "startH": 9,
    "endH": 13,
    "days": "토",
    "dateInfo": "02-07 ~ 02-28",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 20,
    "subject": "게프포폴",
    "instructor": "김홍규",
    "room": "Q",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "02-08 ~ 03-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 21,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 9,
    "endH": 13,
    "days": "토",
    "dateInfo": "01-31 ~ 02-21",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 22,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 14,
    "endH": 18,
    "days": "토",
    "dateInfo": "01-03 ~ 01-31",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 23,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 9,
    "endH": 13,
    "days": "일",
    "dateInfo": "02-01 ~ 02-22",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 24,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 14,
    "endH": 18,
    "days": "일",
    "dateInfo": "01-04 ~ 02-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 25,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 14,
    "endH": 18,
    "days": "일",
    "dateInfo": "02-01 ~ 03-01",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 26,
    "subject": "게임아트웍",
    "instructor": "강진구",
    "room": "R",
    "startH": 14,
    "endH": 18,
    "days": "토",
    "dateInfo": "02-07 ~ 02-28",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 27,
    "subject": "웹소설작가반",
    "instructor": "김나영",
    "room": "S",
    "startH": 9,
    "endH": 13,
    "days": "토/일",
    "dateInfo": "01-10 ~ 02-01",
    "category": "novel",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 28,
    "subject": "웹소설작가반",
    "instructor": "김나영",
    "room": "S",
    "startH": 14,
    "endH": 18,
    "days": "토/일",
    "dateInfo": "01-10 ~ 02-01",
    "category": "novel",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 29,
    "subject": "웹소설작가반",
    "instructor": "김나영",
    "room": "S",
    "startH": 9,
    "endH": 13,
    "days": "토/일",
    "dateInfo": "02-07 ~ 03-01",
    "category": "novel",
    "weekType": "ALL",
    "isBadge": ""
  },
  {
    "id": 30,
    "subject": "웹소설작가반",
    "instructor": "김나영",
    "room": "S",
    "startH": 14,
    "endH": 18,
    "days": "토/일",
    "dateInfo": "02-07 ~ 03-01",
    "category": "novel",
    "weekType": "ALL",
    "isBadge": ""
  }
];