const LECTURE_DATA = [
  {
    "id": 1,
    "subject": "웹툰/토",
    "instructor": "수업없음",
    "room": "M",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 2,
    "subject": "토",
    "instructor": "",
    "room": "M",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-24 ~ 02-21",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 3,
    "subject": "웹툰/일",
    "instructor": "수업없음",
    "room": "M",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 4,
    "subject": "일",
    "instructor": "",
    "room": "M",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "01-25 ~ 02-22",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 5,
    "subject": "웹툰/토",
    "instructor": "수업없음",
    "room": "M",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 6,
    "subject": "토",
    "instructor": "",
    "room": "M",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "02-28 ~ 03-21",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 7,
    "subject": "웹툰/일",
    "instructor": "수업없음",
    "room": "M",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 8,
    "subject": "일",
    "instructor": "",
    "room": "M",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "03-01 ~ 03-22",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 9,
    "subject": "게임원화/주",
    "instructor": "수업없음",
    "room": "O",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 10,
    "subject": "토/일",
    "instructor": "",
    "room": "O",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-21 ~ 03-15",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 11,
    "subject": "게임원화/주",
    "instructor": "수업없음",
    "room": "O",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 12,
    "subject": "토/일",
    "instructor": "",
    "room": "O",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-21 ~ 03-15",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 13,
    "subject": "유니티2/일",
    "instructor": "수업없음",
    "room": "L",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 14,
    "subject": "일",
    "instructor": "",
    "room": "L",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-22 ~ 03-29",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 15,
    "subject": "유니티3/일",
    "instructor": "수업없음",
    "room": "L",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 16,
    "subject": "일",
    "instructor": "",
    "room": "L",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-25 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 17,
    "subject": "유니티1/일",
    "instructor": "수업없음",
    "room": "L",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 18,
    "subject": "일",
    "instructor": "",
    "room": "L",
    "startH": 15,
    "endH": 17,
    "days": "월~금",
    "dateInfo": "03-15 ~ 04-19",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 19,
    "subject": "게임원화/토",
    "instructor": "수업없음",
    "room": "N",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 20,
    "subject": "개강일 1주 연기",
    "instructor": "조성진",
    "room": "N",
    "startH": 11,
    "endH": 13,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 21,
    "subject": "토",
    "instructor": "",
    "room": "N",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "02-21 ~ 03-14",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 22,
    "subject": "스파인/토",
    "instructor": "수업없음",
    "room": "Q",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 23,
    "subject": "토",
    "instructor": "",
    "room": "Q",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-07 ~ 03-07",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 24,
    "subject": "게임그래픽",
    "instructor": "수업없음",
    "room": "Q",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 25,
    "subject": "개강일1주연기",
    "instructor": "최동훈",
    "room": "Q",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 26,
    "subject": "토/일",
    "instructor": "",
    "room": "Q",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-21 ~ 03-15",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 27,
    "subject": "게프포폴/일",
    "instructor": "수업없음",
    "room": "Q",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "port",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 28,
    "subject": "일",
    "instructor": "",
    "room": "Q",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-08 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 29,
    "subject": "스파인/토",
    "instructor": "수업없음",
    "room": "Q",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 30,
    "subject": "토",
    "instructor": "",
    "room": "Q",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "03-14 ~ 04-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 31,
    "subject": "게프포폴/일",
    "instructor": "수업없음",
    "room": "Q",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "port",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 32,
    "subject": "일",
    "instructor": "",
    "room": "Q",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "03-15 ~ 04-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 33,
    "subject": "게임아트웍/토",
    "instructor": "수업없음",
    "room": "R",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 34,
    "subject": "토",
    "instructor": "",
    "room": "R",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-07 ~ 03-07",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 35,
    "subject": "게임아트웍/토",
    "instructor": "수업없음",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 36,
    "subject": "토",
    "instructor": "",
    "room": "R",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-07 ~ 03-07",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 37,
    "subject": "게임아트웍/토",
    "instructor": "수업없음",
    "room": "R",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 38,
    "subject": "토",
    "instructor": "",
    "room": "R",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "03-14 ~ 04-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 39,
    "subject": "게임아트웍/일",
    "instructor": "수업없음",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 40,
    "subject": "일",
    "instructor": "",
    "room": "R",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-08 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 41,
    "subject": "게임아트웍/토",
    "instructor": "수업없음",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 42,
    "subject": "토",
    "instructor": "",
    "room": "R",
    "startH": 15,
    "endH": 17,
    "days": "월~금",
    "dateInfo": "03-14 ~ 04-04",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 43,
    "subject": "게임아트웍/일",
    "instructor": "수업없음",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 44,
    "subject": "일",
    "instructor": "",
    "room": "R",
    "startH": 15,
    "endH": 17,
    "days": "월~금",
    "dateInfo": "03-15 ~ 04-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 45,
    "subject": "아포리아심화반",
    "instructor": "수업없음",
    "room": "P",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 46,
    "subject": "일",
    "instructor": "",
    "room": "P",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-08 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 47,
    "subject": "아포리아심화반",
    "instructor": "수업없음",
    "room": "P",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 48,
    "subject": "일",
    "instructor": "",
    "room": "P",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "03-15 ~ 04-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 49,
    "subject": "게임원화/토",
    "instructor": "수업없음",
    "room": "P",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 50,
    "subject": "토",
    "instructor": "",
    "room": "P",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "01-24 ~ 02-21",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 51,
    "subject": "게임원화/토",
    "instructor": "수업없음",
    "room": "P",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 52,
    "subject": "토",
    "instructor": "",
    "room": "P",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "02-28 ~ 03-21",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 53,
    "subject": "아포리아웹툰데뷔반2",
    "instructor": "수업없음",
    "room": "P",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 54,
    "subject": "일",
    "instructor": "",
    "room": "P",
    "startH": 15,
    "endH": 17,
    "days": "월~금",
    "dateInfo": "03-01 ~ 03-22",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 55,
    "subject": "웹소설작가반/심화",
    "instructor": "수업없음",
    "room": "S",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 56,
    "subject": "토/일",
    "instructor": "",
    "room": "S",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "02-07 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 57,
    "subject": "웹소설작가반",
    "instructor": "수업없음",
    "room": "S",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 58,
    "subject": "토/일",
    "instructor": "",
    "room": "S",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-07 ~ 03-08",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 59,
    "subject": "웹소설작가반/심화",
    "instructor": "수업없음",
    "room": "S",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 60,
    "subject": "토/일",
    "instructor": "",
    "room": "S",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "03-14 ~ 04-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 61,
    "subject": "웹소설작가반",
    "instructor": "수업없음",
    "room": "S",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 62,
    "subject": "토/일",
    "instructor": "",
    "room": "S",
    "startH": 15,
    "endH": 17,
    "days": "월~금",
    "dateInfo": "03-14 ~ 04-05",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 63,
    "subject": "언리얼엔진4/일",
    "instructor": "수업없음",
    "room": "비대면",
    "startH": 10,
    "endH": 12,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 64,
    "subject": "일",
    "instructor": "",
    "room": "비대면",
    "startH": 12,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "01-25 ~ 02-22",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  }
];