[
  {
    "id": 1,
    "subject": "컨셉캐릭터일러/비대면",
    "instructor": "정예지4",
    "room": "M",
    "startH": 12,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 2,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 3,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 4,
    "subject": "웹툰작화(평일)",
    "instructor": "정동호",
    "room": "M",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 5,
    "subject": "게임아트웍",
    "instructor": "심예지",
    "room": "O",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 6,
    "subject": "게임원화",
    "instructor": "심예지",
    "room": "O",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 7,
    "subject": "[국] 게임그래픽 디자인 전문가양성(2D/3D)",
    "instructor": "최동훈, 조성진",
    "room": "L",
    "startH": 9,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "12-01 ~ 07-01",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 8,
    "subject": "게임프로그래밍3",
    "instructor": "최대호",
    "room": "L",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 9,
    "subject": "게임프로그래밍6",
    "instructor": "최대호",
    "room": "L",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 10,
    "subject": "게임프로그래밍2",
    "instructor": "최대호",
    "room": "L",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 11,
    "subject": "게임원화",
    "instructor": "조성진4",
    "room": "N",
    "startH": 11,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 12,
    "subject": "게임아트웍",
    "instructor": "심예지",
    "room": "N",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 13,
    "subject": "스피드드로잉2",
    "instructor": "이재건2",
    "room": "N",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "01-30 ~ 02-12",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 14,
    "subject": "게임아트웍",
    "instructor": "조성진4",
    "room": "N",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 15,
    "subject": "게임원화(심화)",
    "instructor": "조성진4",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 16,
    "subject": "월수금월수",
    "instructor": "",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-11",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 17,
    "subject": "게임아트웍(기초)",
    "instructor": "조성진4",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 18,
    "subject": "화목화목금",
    "instructor": "",
    "room": "N",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-10 ~ 03-06",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 19,
    "subject": "게임그래픽(기초)",
    "instructor": "",
    "room": "Q",
    "startH": 11,
    "endH": 13,
    "days": "월~금",
    "dateInfo": "",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 20,
    "subject": "김지원14",
    "instructor": "",
    "room": "Q",
    "startH": 11,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 21,
    "subject": "게임그래픽(심화)",
    "instructor": "",
    "room": "Q",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 22,
    "subject": "김지원14",
    "instructor": "",
    "room": "Q",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 23,
    "subject": "게임그래픽(심화)",
    "instructor": "",
    "room": "Q",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 24,
    "subject": "김지원14",
    "instructor": "",
    "room": "Q",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 25,
    "subject": "게임그래픽(기초)",
    "instructor": "",
    "room": "Q",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 26,
    "subject": "김지원14",
    "instructor": "김창욱",
    "room": "Q",
    "startH": 18,
    "endH": 20,
    "days": "게임UIUX/격일",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "A",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 27,
    "subject": "월수금월수",
    "instructor": "",
    "room": "Q",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-11",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 28,
    "subject": "화목화목금",
    "instructor": "",
    "room": "Q",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-10 ~ 03-06",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 29,
    "subject": "컨셉캐릭터일러",
    "instructor": "정예지4",
    "room": "R",
    "startH": 9,
    "endH": 11,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 30,
    "subject": "게임아트웍",
    "instructor": "김채민2",
    "room": "R",
    "startH": 11,
    "endH": 14,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 31,
    "subject": "게임원화",
    "instructor": "김채민2",
    "room": "R",
    "startH": 14,
    "endH": 16,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 32,
    "subject": "게임원화",
    "instructor": "김채민2",
    "room": "R",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 33,
    "subject": "웹툰기초드로잉",
    "instructor": "이상원7",
    "room": "R",
    "startH": 18,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 34,
    "subject": "게임아트웍(기초)",
    "instructor": "이재건2",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 35,
    "subject": "월수금월수",
    "instructor": "",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-11",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 36,
    "subject": "게임원화(심화)",
    "instructor": "이재건2",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "",
    "category": "art-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 37,
    "subject": "화목화목금",
    "instructor": "",
    "room": "R",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-10 ~ 03-06",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 38,
    "subject": "컴퓨터그래픽스2",
    "instructor": "김홍규2",
    "room": "P",
    "startH": 11,
    "endH": 14,
    "days": "월/수/금",
    "dateInfo": "01-23 ~ 02-11",
    "category": "graphic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 39,
    "subject": "게임프로그래밍포폴",
    "instructor": "김홍규2",
    "room": "P",
    "startH": 14,
    "endH": 16,
    "days": "화/목",
    "dateInfo": "01-20 ~ 02-12",
    "category": "prog-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 40,
    "subject": "게임기획4",
    "instructor": "전태은",
    "room": "P",
    "startH": 16,
    "endH": 20,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "plan-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 41,
    "subject": "게임기획2",
    "instructor": "전태은",
    "room": "P",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "plan-adv",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 42,
    "subject": "웹툰기초드로잉",
    "instructor": "이상원7",
    "room": "S",
    "startH": 16,
    "endH": 18,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 43,
    "subject": "AI프롬프트드로잉B",
    "instructor": "이재건2",
    "room": "S",
    "startH": 18,
    "endH": 20,
    "days": "화/목",
    "dateInfo": "01-15 ~ 02-10",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 44,
    "subject": "웹툰콘티",
    "instructor": "이상원7",
    "room": "S",
    "startH": 20,
    "endH": 22,
    "days": "월~금",
    "dateInfo": "02-09 ~ 03-10",
    "category": "webtoon",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 45,
    "subject": "AI프롬프트드로잉A2",
    "instructor": "이재건2",
    "room": "S",
    "startH": 18,
    "endH": 20,
    "days": "월/수/금",
    "dateInfo": "02-09 ~ 03-06",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  },
  {
    "id": 46,
    "subject": "AI프롬프트드로잉B",
    "instructor": "이재건2",
    "room": "S",
    "startH": 18,
    "endH": 20,
    "days": "화/목",
    "dateInfo": "02-12 ~ 03-12",
    "category": "art-basic",
    "weekType": "ALL",
    "isBadge": "",
    "fontSize": 14,
    "opacity": 100
  }
]