[
    {
        "id": 1,
        "subject": "컨셉캐릭터일러/비대면",
        "instructor": "정예지",
        "room": "M",
        "startH": 12,
        "endH": 14,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 2,
        "subject": "웹툰작화(평일)",
        "instructor": "정동호",
        "room": "M",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 3,
        "subject": "웹툰작화(평일)",
        "instructor": "정동호",
        "room": "M",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 4,
        "subject": "웹툰작화(평일)",
        "instructor": "정동호",
        "room": "M",
        "startH": 20,
        "endH": 22,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 5,
        "subject": "게임아트웍",
        "instructor": "심예지",
        "room": "O",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-basic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 6,
        "subject": "게임원화",
        "instructor": "심예지",
        "room": "O",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 7,
        "subject": "[국] 게임그래픽 디자인 전문가양성(2D/3D)",
        "instructor": "최동훈, 조성진, 전태은",
        "room": "L",
        "startH": 9,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "12-01 ~ 07-01",
        "category": "graphic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 8,
        "subject": "게임프로그래밍3",
        "instructor": "최대호",
        "room": "L",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "prog-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 9,
        "subject": "게임프로그래밍6",
        "instructor": "최대호",
        "room": "L",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "prog-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 10,
        "subject": "게임프로그래밍2",
        "instructor": "최대호",
        "room": "L",
        "startH": 20,
        "endH": 22,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "prog-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 11,
        "subject": "게임원화",
        "instructor": "조성진",
        "room": "N",
        "startH": 11,
        "endH": 13,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 12,
        "subject": "게임아트웍",
        "instructor": "심예지",
        "room": "N",
        "startH": 14,
        "endH": 16,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-basic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 13,
        "subject": "스피드드로잉2",
        "instructor": "수업없음",
        "room": "N",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "01-30 ~ 02-12",
        "category": "art-basic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 14,
        "subject": "게임아트웍",
        "instructor": "조성진",
        "room": "N",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-basic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 15,
        "subject": "게임원화(심화)",
        "instructor": "수업없음",
        "room": "N",
        "startH": 20,
        "endH": 22,
        "days": "월수금월수",
        "dateInfo": "02-09 ~ 03-11",
        "category": "art-adv",
        "weekType": "B",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 16,
        "subject": "게임아트웍(기초)",
        "instructor": "조성진",
        "room": "N",
        "startH": 20,
        "endH": 22,
        "days": "화목화목금",
        "dateInfo": "02-10 ~ 03-06",
        "category": "art-basic",
        "weekType": "A",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 17,
        "subject": "게임그래픽(기초)",
        "instructor": "김지원",
        "room": "Q",
        "startH": 11,
        "endH": 13,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "graphic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 18,
        "subject": "게임그래픽(심화)",
        "instructor": "김지원",
        "room": "Q",
        "startH": 14,
        "endH": 16,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "graphic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 19,
        "subject": "게임그래픽(심화)",
        "instructor": "김지원",
        "room": "Q",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "graphic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 20,
        "subject": "게임그래픽(기초)",
        "instructor": "김지원",
        "room": "Q",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "graphic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 21,
        "subject": "게임UIUX",
        "instructor": "김창욱",
        "room": "Q",
        "startH": 20,
        "endH": 22,
        "days": "월수금월수",
        "dateInfo": "02-09 ~ 03-11",
        "category": "ui",
        "weekType": "B",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 22,
        "subject": "이모티콘",
        "instructor": "김창욱",
        "room": "Q",
        "startH": 20,
        "endH": 22,
        "days": "화목화목금",
        "dateInfo": "02-10 ~ 03-06",
        "category": "emo",
        "weekType": "A",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 23,
        "subject": "컨셉캐릭터일러",
        "instructor": "정예지",
        "room": "R",
        "startH": 9,
        "endH": 11,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 24,
        "subject": "게임아트웍",
        "instructor": "김채민",
        "room": "R",
        "startH": 11,
        "endH": 13,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-basic",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 25,
        "subject": "게임원화",
        "instructor": "김채민",
        "room": "R",
        "startH": 14,
        "endH": 16,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 26,
        "subject": "게임원화",
        "instructor": "김채민",
        "room": "R",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "art-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 27,
        "subject": "웹툰기초드로잉",
        "instructor": "이상원",
        "room": "R",
        "startH": 18,
        "endH": 20,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 28,
        "subject": "게임아트웍(기초)",
        "instructor": "이재건",
        "room": "R",
        "startH": 20,
        "endH": 22,
        "days": "월수금월수",
        "dateInfo": "02-09 ~ 03-11",
        "category": "art-basic",
        "weekType": "B",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 29,
        "subject": "게임원화(심화)",
        "instructor": "이재건",
        "room": "R",
        "startH": 20,
        "endH": 22,
        "days": "화목화목금",
        "dateInfo": "02-10 ~ 03-06",
        "category": "art-adv",
        "weekType": "A",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 32,
        "subject": "게임기획4",
        "instructor": "전태은",
        "room": "P",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "plan-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 33,
        "subject": "게임기획2",
        "instructor": "전태은",
        "room": "P",
        "startH": 20,
        "endH": 22,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "plan-adv",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 34,
        "subject": "웹툰기초드로잉",
        "instructor": "이상원",
        "room": "S",
        "startH": 16,
        "endH": 18,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 35,
        "subject": "AI프롬프트드로잉",
        "instructor": "이재건",
        "room": "S",
        "startH": 18,
        "endH": 20,
        "days": "화목월수금",
        "dateInfo": "01-15 ~ 02-10",
        "category": "art-basic",
        "weekType": "A",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    },
    {
        "id": 36,
        "subject": "웹툰콘티",
        "instructor": "이상원",
        "room": "S",
        "startH": 20,
        "endH": 22,
        "days": "월~금",
        "dateInfo": "02-09 ~ 03-10",
        "category": "webtoon",
        "weekType": "ALL",
        "isBadge": "",
        "fontSize": 14,
        "opacity": 100
    }
]